name : firstAction
on :
    push : 
        branches : main
jobs : 
    build : 
        runs-on : ubuntu-latest
        steps : 
          - name: Send Telegram Notification
            uses: appleboy/telegram-action@master
            with:
              to: ${{ secrets.ChatID }}
              token: ${{ secrets.BotToken }}
              message: "Hello from GitHub Actions!"

          - name: saludar
            run: echo "Hello, world!"
          - name : despedirse
            run : echo "good bye!"