name : firstAction
on :
    push : 
        branches : main
jobs : 
    build : 
        runs-on : ubuntu-latest
        steps : 
          - name: notification
            if: cancelled() == false
            uses: xinthink/action-telegram@v1.1
            with:
              botToken: ${{ secrets.BotToken }}
              chatId: ${{ secrets.ChatID }}
              jobStatus: ${{ job.status }}
          - name: saludar
            run: echo "Hello, world!"
          - name : despedirse
            run : echo "good bye!"