name : firstAction
on :
    push : 
        branches : main
jobs : 
    build : 
        runs-on : ubuntu-latest
        steps : 
          - name: Send Telegram Notification
            uses: appleboy/telegram-action@master
            with:
              to: ${{ secrets.ChatID }}
              token: ${{ secrets.BotToken }}
              message: |
                ${{ github.actor }} created commit:
                Commit message: ${{ github.event.commits[0].message }}
                
                Repository: ${{ github.repository }}
                
                See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

